### ISSUE TITLE
Unable to execute echo command

### ISSUE THREAD

**Issue by faraazahmad** [faraazahmad/shellrb#22]
on running `echo`, the output is
>`Command 'echo' not found

indicating it is unable to access the `Echo` class

**Comment by pknight24** [comment]
What system are you trying it on? It worked on both Mac and Linux for me.

**Comment by faraazahmad** [comment]
x86_64 Linux 4.10.0-32-generic
Bundler version 1.15.4
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
Ubuntu 17.04 zesty

**Comment by faraazahmad** [comment]
Re-cloned the repo it works now.
