### ISSUE TITLE
Adding a License

### ISSUE THREAD

**Issue by pknight24** [faraazahmad/shellrb#28]
I am not sure if this is the right place to bring this up, but I think that it would be a good idea to add a license to shellrb, in case anyone wants to use anything that we write.

**Comment by faraazahmad** [comment]
This is a really important issue. Is there any license that basically says, "use it however you like but give attribution"?

**Comment by pknight24** [comment]
I think that the Apache License would be best for that. Here is a list if you want to read more before deciding on a license to use: https://opensource.org/licenses

**Comment by Doshirae** [comment]
Basically, as far as I know, there's : 
- GPL → do whatever you want with that, juste don't use close it (don't use it in proprietary code)
- MIT → Do what you want, just credit the original sources
- Apache → Same as MIT but "also provides an express grant of patent rights from contributors to users."
- WTFPL → Litterally "Do What the Fuck You Want to Public License"
Github made a nice tool to choose one https://choosealicense.com/

**Comment by faraazahmad** [comment]
Added MIT License in #38
