### ISSUE TITLE
Having a `help` command

### ISSUE THREAD

**Issue by Doshirae** [faraazahmad/shellrb#33]
I think it would be neat if there were a `help` command that lists all possible command since there's currently no way to know, except to search the *lib/* folder.

I could maybe try to implement that, but I don't know how to figure it out yet

**Comment by faraazahmad** [comment]
Yeah that's a sweet idea! I was actually considering it myself

**Comment by sirsnowy7** [comment]
I _might_ be able to help on this one, it sounds like a great idea. It would probably attract users, even more so if every specific command had a help page, such as the man pages do.

**Comment by ptangphao** [comment]
Gave it a shot and would appreciate any comments. Had some issues with the RSPEC since it requires the directory.
