### ISSUE TITLE
Help command works when inside the project directory

### ISSUE THREAD

**Issue by faraazahmad** [faraazahmad/shellrb#37]
If you are outside the root directory, the help command does not produce output

**Comment by ptangphao** [comment]
Thinking of solving this using a class variable that I would create using Dir.pwd when it instantiates. Then, each time the method gets called, it saves the current directory, changes the directory to the saved class variable, outputs the entries, and then switches the directory back. Thoughts?

**Comment by faraazahmad** [comment]
Sounds good! Can you show a working prototype?

**Comment by ptangphao** [comment]
Looks like you found a better solution! Changing from 

```ruby
Dir.entries('lib/packages')
``` 

to 

```ruby
File.dirname(__FILE__)
```

Looks to have taken care of the issue. My understanding is that 'File.dirname(__FILE__)' gives us the directory of the help file which means that no matter what directory we're in, we're able to reference the correct directory!

**Comment by faraazahmad** [comment]
Good catch! It's also in `require.rb`
