### ISSUE TITLE
Create mkdir using FileUtils

### ISSUE THREAD

**Issue by faraazahmad** [faraazahmad/shellrb#40]
[FileUtils](http://ruby-doc.org/stdlib-2.4.2/libdoc/fileutils/rdoc/FileUtils.html) is a powerful module for dealing with files and would make it very easy to build file based functionality into shellrb. The current `mkdir` class is written using `Dir`, it would be better and more consistent to just rely on the `fileutils` library

**Comment by faraazahmad** [comment]
@ekeast

**Comment by alagram** [comment]
@faheel I'd like to take this up if no one is currently working on it.

**Comment by faraazahmad** [comment]
@alagram would you still be interested in working on this?

**Comment by alagram** [comment]
@faheel yes I'll get started right away.

**Comment by faheel** [comment]
@alagram Why did you mention me here 😄

**Comment by alagram** [comment]
Oops @faheel . That was meant was meant for @faraazahmad  😄
