### ISSUE TITLE
Create copy (cp) command using FileUtils

### ISSUE THREAD

**Issue by faraazahmad** [faraazahmad/shellrb#41]
[FileUtils](http://ruby-doc.org/stdlib-2.4.2/libdoc/fileutils/rdoc/FileUtils.html) is a powerful module for dealing with files and would make it very easy to build file based functionality into shellrb.

First write the tests, then create the copy command to copy files, or directory to make the tests pass

**Comment by zomblake** [comment]
I have a working version of this implemented. It needs some polishing, but do you mind if I submit a PR after I get it 100 percent?

**Comment by faraazahmad** [comment]
You could do that, or you could just publish the PR and I'll help you out! :smile:

**Comment by tacoda** [comment]
👋 Following up on this, it seems like this issue has become stale. If so, I'd like to start working on a PR for it.

**Comment by faraazahmad** [comment]
Yes thank you! Go for it! Let me know if you need help

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
