### ISSUE TITLE
Write tests for mkdir 

### ISSUE THREAD

**Issue by faraazahmad** [faraazahmad/shellrb#42]
Write failing tests for `mkdir` which can then be passed in #40

**Comment by faraazahmad** [comment]
Info on writing tests can be found [here](https://github.com/faraazahmad/shellrb/blob/master/CONTRIBUTING.md#test-files)

**Comment by ekeast** [comment]
I have made the tests as well as made a package for mkdir. Can I submit a pull request?

**Comment by faraazahmad** [comment]
of course!

**Comment by faraazahmad** [comment]
Done in #44
